name: aic
services:
  eval:
    image: ghcr.io/intrinsic-dev/aic/aic_eval
    # image: my-eval:v1
    build:
      dockerfile: docker/aic_eval/Dockerfile
      context: ..
    command: gazebo_gui:=False launch_rviz:=true ground_truth:=true start_aic_engine:=true shutdown_on_aic_engine_exit:=true model_discovery_timeout_seconds:=600
    gpus: all
    networks:
      - default
    environment:
      AIC_EVAL_PASSWD: CHANGE_IN_PROD
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
      DISPLAY: $DISPLAY
      # NVIDIA services para mejorar el rendimiento gráfico en contenedores
      # NVIDIA_DRIVER_CAPABILITIES: all
      # NVIDIA_VISIBLE_DEVICES: all
      # MESA_D3D12_DEFAULT_ADAPTER_NAME: NVIDIA
      # GZ_SIM_RENDER_ENGINE: ogre2
      # # LP_NUM_THREADS: 8
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # AIC_ENABLE_ACL: true
  model:
    image: my-solution:v1
    build:
      dockerfile: docker/aic_model/Dockerfile
      context: ..
    gpus: all
    networks:
      - default
    environment:
      RMW_IMPLEMENTATION: rmw_zenoh_cpp
      ZENOH_ROUTER_CHECK_ATTEMPTS: -1
      AIC_ROUTER_ADDR: eval:7447
      AIC_CAMERA_OUTPUT_DIR: /ws_aic/src/aic/aic_camera_data
      # AIC_ROUTER_ADDR: 172.31.72.84:7447
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
      # AIC_ENABLE_ACL: true
    volumes:
      - ../aic_camera_data:/ws_aic/src/aic/aic_camera_data
networks:
  default:
    internal: false
